name: flutter_voximplant
description: Voximplant plugin for embedding voice and video communication into Flutter applications.
version: 2.1.1
authors:
  - Voximplant Team <mobiledev@zingaya.com>
  - Yulia Grigorieva <grigorieva@voximplant.com>
  - Alexander Filippov <afilippov@voximplant.com>
homepage: https://voximplant.com
repository: https://github.com/voximplant/flutter_voximplant

environment:
  sdk: ">=2.2.0 <3.0.0"
  flutter: ">=1.10.0 <2.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: com.voximplant.flutter_voximplant
        pluginClass: VoximplantPlugin
      ios:
        pluginClass: VoximplantPlugin
