name: flutter_voximplant
description: Voximplant plugin for embedding voice and video communication into Flutter applications.
version: 3.3.0
homepage: https://voximplant.com
repository: https://github.com/voximplant/flutter_voximplant

environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: ">=1.20.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  e2e: 0.6.0
  flutter_driver:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: com.voximplant.flutter_voximplant
        pluginClass: VoximplantPlugin
      ios:
        pluginClass: VoximplantPlugin
